### ISSUE TITLE
New echelon stride treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#2555]
![image](https://github.com/user-attachments/assets/852a33a3-6072-4753-b2de-915f5489ea9a)

**Comment by mbfit1** [comment]
[debug-Fri_Aug_30_14_10_42_2024.log](https://github.com/user-attachments/files/16820979/debug-Fri_Aug_30_14_10_42_2024.log)
[debug-Fri_Aug_30_14_09_04_2024.log](https://github.com/user-attachments/files/16820980/debug-Fri_Aug_30_14_09_04_2024.log)

**Comment by cagnulein** [comment]
Ok I got the issue.
This version seems different from the others
Do you have an android device to collect some logs with the echelon app?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 30 ago 2024 alle 20:32 mbfit1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Can you also share a full screenshot from nrfconnect showing all the characteristics from the treadmill?

**Comment by mbfit1** [comment]
No unfortunately I do not. If this helps I started a temp echelon membership account. Ech app not running when I was trying to connect QZ and Pelo. However the stride connects with ech app no problem

**Comment by cagnulein** [comment]
> Can you also share a full screenshot from nrfconnect showing all the characteristics from the treadmill?

Ok let's start with this

**Comment by cagnulein** [comment]
> [debug-Fri_Aug_30_14_10_42_2024.log](https://github.com/user-attachments/files/16820979/debug-Fri_Aug_30_14_10_42_2024.log)
> 
> [debug-Fri_Aug_30_14_09_04_2024.log](https://github.com/user-attachments/files/16820980/debug-Fri_Aug_30_14_09_04_2024.log)
> 
> 

I was checking again these 2 logs and here the virtual Bluetooth device is still enabled. Please disable it and if you have still the issue, upload a fresh debug log
Thanks

**Comment by mbfit1** [comment]
MarcOn Aug 30, 2024, at 3:50 PM, Roberto Viola ***@***.***> wrote:﻿

debug-Fri_Aug_30_14_10_42_2024.log
debug-Fri_Aug_30_14_09_04_2024.log

I was checking again these 2 logs and here the virtual Bluetooth device is still enabled. Please disable it and if you have still the issue, upload a fresh debug log
Thanks

**Comment by cagnulein** [comment]
You have to attach file on github web interface directly otherwise I can't see them. i'm going to bed now. i will check them tomorrow anyway
have a nice evening!

**Comment by cagnulein** [comment]
[STRIDE40SPT-000441.txt](https://github.com/user-attachments/files/16821643/STRIDE40SPT-000441.txt)

**Comment by mbfit1** [comment]
Ok thanks so much..  

 

Marc

404.285.5671

**Comment by mbfit1** [comment]
[debug-Fri_Aug_30_16_08_02_2024.log](https://github.com/user-attachments/files/16821840/debug-Fri_Aug_30_16_08_02_2024.log)
[debug-Fri_Aug_30_16_08_02_2024.log](https://github.com/user-attachments/files/16821846/debug-Fri_Aug_30_16_08_02_2024.log)

**Comment by cagnulein** [comment]
Ok so echelon definitely changed the protocol for this treadmill? Is it a brand new model right? We strictly need an android device, even an old one, with the echelon app following this https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Could you be able to find one?

**Comment by mbfit1** [comment]
The tread is Ech Stride 40 sport. Not sure it is new.
Would an android tablet work? I might be able to find one

**Comment by cagnulein** [comment]
Yes, it does'


Il giorno sab 31 ago 2024 alle 13:32 mbfit1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Hi @mbfit1 Any news?

**Comment by mbfit1** [comment]
Hi Roberto,

I did not get an android yet, was Labor Day long weekend here in US and did not focus on the issue, but will today. 

Thanks for being persistent. 

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
No worries, thanks for the update!


Il giorno mar 3 set 2024 alle 13:06 mbfit1 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
it should works also with an amazon tablet but i never tried, no you don't
need the qz app there, just the echelon app

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle ore 17:11 mbfit1 ***@***.***>
ha scritto:

**Comment by mbfit1** [comment]
The echelon app is not available from Amazon app store for Fire HD Tablet. Ill have to find another Android.

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
can't you download the apk from apk pure?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 21:17 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Well I’m not sure. However the info I got was from the Echelon FAQ where they said app does not work on an Amazon Fire.

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
ok for sure if you can try with another android device it's better

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 21:49 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
I have a galaxy android tablet that is running Echelon app.

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
that's perfect

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 set 2024 alle 13:00 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
I tried everything again and QZ dropping Pelo class.

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
i don't understand: you should use the echelon app there to get the hci
snoof without qz following this
https://github.com/cagnulein/qdomyos-zwift/blob/master/docs/20_supported_devices_and_applications.md#android-device

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 set 2024 alle 14:04 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Sorry about the confusion. I hope the attached helps

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
Hi @mbfit1 nope, I need the bug reports file or at least the hci snoof log. Didn't create it?

**Comment by mbfit1** [comment]
Hi Roberto,

I run the log and I can't find it. I'm new to Android. Looking everywhere..

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
Did you receive the notification from the android device telling that the
report is ready?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle 12:36 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
It said “screenshot taken with bug report” where is this hiding?  I hit it and nothing happens.. nothing opens.

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
There is a share button there that you can use to send it by email

**Comment by mbfit1** [comment]
Hope you can read this one.

[bugreport-gta7litewifieea-UP1A.231005.007-2024-09-12-19-23-59.zip](https://github.com/user-attachments/files/16993758/bugreport-gta7litewifieea-UP1A.231005.007-2024-09-12-19-23-59.zip)

**Comment by cagnulein** [comment]
yes it seems perfect! i'm adding the patch! i will let you know when i will
be ready!
hopefully today!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle ore 14:25 mbfit1 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mbfit1 in the echelon app were you able to change speed or inclination directly from the app?

**Comment by cagnulein** [comment]
also did you run it to 1 mi/h all the time? @mbfit1 
and did you change the inclination or it was always 0%?

**Comment by mbfit1** [comment]
I see why you are asking. I launched everything and walked away from the
tread. I will gladly do it again  for 5 minutes, test app to make changes
and send another bug file. 

Let me know, not a big deal...

 

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
ok let's try the version that I sent you right now. in case we can collect another one if i have some other doubts

**Comment by mbfit1** [comment]
You want me to run the Peloton App or Echelon App?

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
just qz with the new build that I just sent you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle ore 15:42 mbfit1 ***@***.***>
ha scritto:

**Comment by mbfit1** [comment]
[debug-Fri_Sep_13_13_40_17_2024.log](https://github.com/user-attachments/files/16997743/debug-Fri_Sep_13_13_40_17_2024.log)
[debug-Fri_Sep_13_13_40_17_2024.log](https://github.com/user-attachments/files/16997750/debug-Fri_Sep_13_13_40_17_2024.log)

**Comment by cagnulein** [comment]
Thanks! I will check it ASAP, don't worry we will get it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 13 set 2024 alle 19:58 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
No worries.. I'm getting the hang of this! learning something new.. LOL

**Comment by cagnulein** [comment]
Hi @mbfit1 i checked the log and you didn't install the build 864 from testflight. Don't you get the email? Check also the testflight app for an update!
Let me know

**Comment by mbfit1** [comment]
No I did not get an email. However 857 is the last build in TestFlight. Do I need a redemption code? 

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
I sent it here
boyerm at bellsouth.net


Is it right? Check the span in case or send me another account email since
I can't send the same version twice to the same user

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 14 set 2024 alle 14:17 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Yes ***@***.*** ***@***.***>  is correct. Not in spam. I receive all your communications at ***@***.*** Try ***@***.*** 

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
Github is hiding it, use the at instead of the @

anyway check also the spam

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 14 set 2024 alle 14:32 mbfit1 ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Still can't find it anywhere sorry., trying

**Comment by cagnulein** [comment]
as i said github filtered your last message, you need to write your other
email account replacing the @ with at

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 14 set 2024 alle 17:30 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Mbfit2 at icloud.com 
Sorry took me a minute to figure out what you were asking me to do ....sorry...

**Comment by cagnulein** [comment]
Ahahah don't worry! Sent!

**Comment by mbfit1** [comment]
New problem 
![image](https://github.com/user-attachments/assets/7a6ef321-7bb3-4676-b591-249dd546ee8e)

**Comment by cagnulein** [comment]
This time is Apple fault, we need to wait some minutes :)

**Comment by mbfit1** [comment]
Same error this morning. I'll be on and off computer today. Hope you having great Sunday.

**Comment by cagnulein** [comment]
sent also again here

boyerm at bellsouth.net


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 15 set 2024 alle 13:28 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Got from mbfit2 but got new error
![image](https://github.com/user-attachments/assets/10e26608-bde7-4551-879d-6220fa2bf283)

**Comment by cagnulein** [comment]
Where are you from? Testflight here in Italy  is working.

**Comment by mbfit1** [comment]
USA Georgia

**Comment by cagnulein** [comment]
It's still doesn't work? I sent plenty of invites in these days and all are working. Mayhe it's something about your wifi? Did you try also with the mobile network?

**Comment by mbfit1** [comment]
Still not working I tried no Wi-Fi, dumped and restored TestFlight app too.

**Comment by cagnulein** [comment]
i don't know what to say. the only way to send you a newer version is testflight. did you also try to another device?

**Comment by mbfit1** [comment]
No I did not. I will try. Give me a few days. I have a couple of IPADS. Thanks for hanging in there.

**Comment by mbfit1** [comment]
Got the redeem code to work on IPAD Pro. Im not sure if the QZ app got updated. Can you tell from the debug log attached?
[debug-Tue_Sep_17_14_16_03_2024.log](https://github.com/user-attachments/files/17043855/debug-Tue_Sep_17_14_16_03_2024.log)

**Comment by cagnulein** [comment]
yes it's updated finally. i will check the debug log, from a first saw it
seems that it's still doesn't work. i will check it asap, im on a business
trip

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 18 set 2024 alle 14:24 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
sounds good Thanks

**Comment by cagnulein** [comment]
@mbfit1 can you try to disable the virtual bluetooth device setting in the experimental settings and try again? if it doesn't work send me a fresh log anyway
Thanks!

**Comment by mbfit1** [comment]
#- [ ] - [_~~~~_]()~~

**Comment by mbfit1** [comment]
done. Still dropped the connection
[debug-Thu_Sep_19_08_31_51_2024.log](https://github.com/user-attachments/files/17059278/debug-Thu_Sep_19_08_31_51_2024.log)

**Comment by cagnulein** [comment]
mmm it seems they added a sort of authorization key on bluetooth. i have to figure this out. I guess echelon is trying to blocking QZ after all these years. Let's see if i can workaround this

**Comment by mbfit1** [comment]
[bugreport-gta7litewifieea-UP1A.231005.007-2024-09-19-13-46-20.zip](https://github.com/user-attachments/files/17063839/bugreport-gta7litewifieea-UP1A.231005.007-2024-09-19-13-46-20.zip)

**Comment by cagnulein** [comment]
ok at least the key is not rolling over

Value: f0e0728518586198

let me try to check if i can handle this

**Comment by mbfit1** [comment]
ok sounds good. Thanks for keep trying.

**Comment by cagnulein** [comment]
new version sent!
fingers crossed!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle ore 12:37 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
What email? Bellsouth, Gmail or iCloud? Do not have TestFlight invite anywhere?

**Comment by cagnulein** [comment]
bellsouth.net


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 17:40 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
looked everywhere.. all folders. last success was with icloud. Try that one mbfit2.

**Comment by mbfit1** [comment]
got it, loaded, tested, dropped 
[debug-Fri_Sep_20_15_26_45_2024.log](https://github.com/user-attachments/files/17080134/debug-Fri_Sep_20_15_26_45_2024.log)

**Comment by cagnulein** [comment]
ok we did a step forward! it's talking! i will check it deeply in the next
days
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 21:39 Marc ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
can't you start the treadmill even from the treadmill itself with qz
connected?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 21:40 cagnulein ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
Yes I start the treadmill.. then i launch QZ. QZ finds the tread, just doesn't hang on to it.. drops it about 15 seconds

**Comment by cagnulein** [comment]
ok i will check it, we are going forward

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 set 2024 alle 21:52 Marc ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> drops it about 15 seconds

@mbfit1 what do you mean? in the log i can see the connection is strong for the whole 3 minute session. was the treadmill run at a speed greater than 0 during the log?

**Comment by cagnulein** [comment]
i guess what it's going on here. echelon generates the key based on the device that it's connecting on. to prove this, could you please install this version of qz https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk on the same android that you are using to collect the hci snoof. than just check if it's working and in any case share me a debug log.

If i'm right, i have to decrypt the algorithm that they are using
Let me know
Thanks for all the work

**Comment by mbfit1** [comment]
To answer your first question, yes i bumped tread speed up several times and the incline too during that session. I will load QZ per your instruction. I'll let you know, No problem helping. Its interesting.
Ill be away from computer for a good part of today. Working outside closing pool down for season, yardwork.. etc etc
My pleasure to help

**Comment by cagnulein** [comment]
Sounds good, thanks!
i will be away too today!

Il giorno sab 21 set 2024 alle 14:01 Marc ***@***.***> ha
scritto:

**Comment by mbfit1** [comment]
[debug-Sat_Sep_21_13_05_26_2024.log](https://github.com/user-attachments/files/17085121/debug-Sat_Sep_21_13_05_26_2024.log)

**Comment by mbfit1** [comment]
See QZ debug, still dropping
[debug-Fri_Sep_27_07_51_05_2024.log](https://github.com/user-attachments/files/17163822/debug-Fri_Sep_27_07_51_05_2024.log)

**Comment by cagnulein** [comment]
@mbfit1 i didn't sent the version for a specific fix of this treadmill, i was waiting for 

> i guess what it's going on here. echelon generates the key based on the device that it's connecting on. to prove this, could you please install this version of qz https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk on the same android that you are using to collect the hci snoof. than just check if it's working and in any case share me a debug log.

> If i'm right, i have to decrypt the algorithm that they are using

**Comment by cagnulein** [comment]
nope because i would like to test it on the same android device where you collected the hci snoof using the apk in the link

**Comment by mbfit1** [comment]
[debug-Fri_Sep_27_08_43_34_2024.log](https://github.com/user-attachments/files/17164384/debug-Fri_Sep_27_08_43_34_2024.log)

**Comment by cagnulein** [comment]
ok it has a different behaviour on the bluetooth side on android. i have to
study this, I will let you know when I will have something new to try
Thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 27 set 2024 alle ore 14:57 Marc ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> ok at least the key is not rolling over
> 
> Value: f0e0728518586198
> 
> let me try to check if i can handle this

I was wrong, it's rolling

tx from treadmill Value: f0e0728518586198
tx from phone Value: f0e091f8241453e4

tx from treadmill Value: f0e01013134967b6
tx from phone Value: f0e0fd3e6548d58d

So they are doing some sort of operation on this number, I have to crack this

**Comment by mbfit1** [comment]
I know you can do it!

**Comment by cagnulein** [comment]
I started a brute force script that it will run the whole weekend, hopefully we will have an answer next week. it's a huge job for this computer now :)

**Comment by mbfit1** [comment]
Sounds scary but cool. Good luck.. Let me know when I need to do something. 👍

**Comment by cagnulein** [comment]
@mbfit1 I didn't forget about you: the CPU brute force approach it was too slow (ETA 2 years) so i switched to the GPU approach and we should have a result in a week

**Comment by mbfit1** [comment]
No problem Roberto, let me know when you need something from me. We will get it.

**Comment by cagnulein** [comment]
note for me 

AbstractC12792b

**Comment by cagnulein** [comment]
I didn't forget about this, I just need some free mind time, unfortunately
in autumn and winter is rare :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 28 ott 2024 alle 22:20 stale[bot] ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
another model crypted 
[debug-Fri_Dec_13_20_33_32_2024.log](https://github.com/user-attachments/files/18131814/debug-Fri_Dec_13_20_33_32_2024.log)

**Comment by cagnulein** [comment]
@d3m3vilurr sorry to ping you: this treadmill exchange a key between the treadmill and the app, and then they are cypting the communication. I have the hci snoof from the original app, and unfortunately the app is well obfuscated. Have you ever see something like this? The only thing that comes to my mind is trying to debug it in somehow but it will need a real treadmill or at least a simulator. Let me know if you have any ideas

**Comment by mbfit1** [comment]
Thanks for trying. I don't have any ideas. Sorry

**Comment by cagnulein** [comment]
Yeah @mbfit1 I was talking with @d3m3vilurr

**Comment by d3m3vilurr** [comment]
sorry i just read it today.
i'll check it tonight :)

**Comment by cagnulein** [comment]
thanks @d3m3vilurr happy new year!

**Comment by d3m3vilurr** [comment]
@cagnulein happy new year!

----

I just read [bt log](https://github.com/cagnulein/qdomyos-zwift/issues/2555#issuecomment-2348832675) as quite roughly; 

<details>
<summary>bt log id 505 ~ 756</summary>

```
16 << f0 e0 72 85 18 58 61 98 ; 505
...

11 >> f0 a4 00 94
11 <<
11 >> f0 e0 91 f8 24 14 53 e4
11 <<
11 >> f0 a4 00 94
11 <<
13 << f0 a4 01 00 95
11 >> f0 a1 00 91
11 <<
11 >> f0 a1 00 91
13 << f0 a1 07 20 76 00 a7 07 ff 01 dc
11 <<
11 >> f0 a1 00 91
13 << f0 a1 07 20 76 00 a7 07 ff 01 dc
11 <<
11 >> f0 a1 00 91
13 << f0 a1 07 20 76 00 a7 07 ff 01 dc
11 <<
11 >> f0 a3 00 93
13 << f0 a1 07 20 76 00 a7 07 ff 01 dc
11 <<
11 >> f0 b0 01 01 a2
13 << f0 a3 07 0f 00 30 70 01 f4 00 3e
11 <<
11 >> f0 a5 00 95
16 << f0 d0 01 00 c1 ; 553
16 << f0 d0 01 11 d2 ; 554
11 <<
11 >> f0 d0 01 00 c1 ; 553 -> 556
16 << f0 d3 02 01 f4 ba ; 558
13 << f0 a5 01 00 96
11 <<
11 >> f0 d0 01 11 d2 ; 554 -> 567
11 <<
11 >> f0 d3 02 01 fa b4 ; 558 -> 572
11 <<
16 << f0 d1 09 00 00 00 00 00 00 00 00 00 ca ; 606
11 >> f0 a0 01 01 92 ; 609
11 <<
13 << f0 a0 01 01 92 ; 609 -> 612
16 << f0 d1 09 00 00 00 00 00 00 00 00 00 ca
16 << f0 d1 09 00 00 00 00 00 00 00 00 00 ca
16 << f0 d0 01 01 c2 ; 631
11 >> f0 d0 01 01 c2 ; 631 -> 632
11 <<
11 >> f0 a0 01 02 93 ; 637
11 <<
13 << f0 a0 01 02 93 ; 637 -> 640
16 << f0 d1 09 00 01 00 00 00 00 00 00 00 cb ; flag changed
16 << f0 d1 09 00 02 00 00 00 00 00 00 00 cc ; flag changed
11 >> f0 a0 01 03 94 ; 656
11 <<
13 << f0 a0 01 03 94 ; 656 -> 659
16 << f0 d1 09 00 03 00 00 00 00 00 00 00 cd
16 << f0 d1 09 00 04 00 00 00 00 00 00 00 ce
11 >> f0 a0 01 04 95 ; 
11 <<
13 << f0 a0 01 04 95
16 << f0 d1 09 00 05 00 00 00 00 00 00 00 df
16 << f0 d5 01 02 c8
16 << f0 d1 09 00 06 00 00 00 00 00 00 00 d0
11 >> f0 a0 01 05 96
11 <<
13 << f0 a0 01 05 96
16 << f0 d1 09 00 07 00 00 00 00 00 00 00 d1
16 << f0 d3 02 02 58 1f ; 716
11 >> f0 d3 02 02 58 1f ; 716 -> 717
11 <<
16 << f0 d3 02 02 bc 83 ; 720
11 >> f0 d3 02 02 bc 83 ; 720 -> 721
11 <<
16 << f0 d1 09 00 08 00 00 00 00 00 00 00 d2
16 << f0 d3 02 03 20 e8 ; 725
11 >> f0 d3 02 03 20 e8 ; 725 -> 726
11 <<
16 << f0 d3 02 03 84 4c ; 729
11 >> f0 d3 02 03 84 4c ; 729 -> 730
11 <<
11 >> f0 a0 01 06 97 ; 735
11 <<
13 << f0 a0 01 06 97 ; 738
16 << f0 d1 09 00 09 00 00 00 00 00 00 00 d3
16 << f0 d2 01 01 c4 ; 754
11 >> f0 d2 01 01 c4 ; 754 -> 755
16 << f0 01 09 00 0a 00 00 00 00 00 00 00 d4
```
</details>


## expected code table

```
handle 0x11
- f0 a0 01 xx yy            ; xx (0x01~) yy (0x92~) - unk - data poll req?
- f0 a1 00 91               ; init step 3, 4, 5, 6
- f0 a3 00 93               ; init step 7
- f0 a4 00 94               ; init step 0, 2
- f0 a5 00 95               ; init step 9
- f0 b0 01 01 a2            ; init step 8
- f0 d0 xx xx xx            ; echo res of req 0x16
- f0 d2 xx xx xx            ; echo res of req 0x16
- f0 d3 xx xx xx xx         ; echo res of req 0x16
- f0 e0 91 f8 24 14 53 e4   ; init step 1

handle 0x13
- f0 a0 xx xx xx                            ; echo res of req 0x11
- f0 a1 xx xx xx xx xx xx xx xx xx          ; res of init step 3...
- f0 a3 xx xx xx xx xx xx xx xx xx          ; res of init step 7
- f0 a4 01 00 94                            ; res of init step 2
- f0 a5 xx xx xx                            ; res of init step 9

handle 0x16
- f0 d0 xx xx xx                            ; req
- f0 d1 09 00 xx 00 00 00 00 00 00 00 yy    ; xx (0x00~) yy (0xca~) ; unk - res poll?
- f0 d2 xx xx xx                            ; req
- f0 d3 xx xx xx xx                         ; req
- f0 d5 xx xx xx                            ; unk
```

## my expectation

imo, a codeset is looks already fully implemented.
just imo, there has something missing part such as index handling.
and also first initialize code would be different.

log uses `f0 e0 91 f8 24 14 f3 e4` but you use `f0 e0 fd 3e 65 48 d5 8d` (if you copied correctly, it might diff each time or just another encryption)

----

ah I got it. I misunderstand your request. I read your [message](https://github.com/cagnulein/qdomyos-zwift/issues/2555#issuecomment-2379269552) now.

yeah... we have to crack the this encryption rule of the `f0 e0` hm.....

----

well. i have to resetup reversing environment in my computer (but sorry i'm lazy and idk eta :( ) and also i don't know correct echelon app(echelonfit ?)

if an app is `echelon fit`, we have to find kotlen decompiler tool like [vineflower](https://github.com/Vineflower/vineflower) instead java decompilers.
that because, old java decompilers couldn't decompile whole bytecodes. (i didn't know that until this time.)

anyway, a java class would be `com.echelonfit.equipment.encryption.UnlockEquipment`..

**Comment by cagnulein** [comment]
I didn't know vineflower till now!
I will check it and I will let you know if I will find something useful

Thanks for the help!
And happy new year!

**Comment by cagnulein** [comment]
@d3m3vilurr i just checked vineflower against the apk but it doesn't decrypt anything at all. am I missing a step?

**Comment by cagnulein** [comment]
got it from Claude.ai

I'll help you decompile an APK using Vineflower. For this we'll need to:

1. Extract the APK's classes.dex files
2. Convert them to .jar format
3. Use Vineflower to decompile the .jar

Here's the step-by-step process:

1. First, install dex2jar and Vineflower:
```bash
# For dex2jar (if not already installed)
git clone https://github.com/pxb1988/dex2jar
cd dex2jar
./gradlew distZip

# For Vineflower
git clone https://github.com/Vineflower/vineflower
cd vineflower
./gradlew build
```

2. Extract the classes.dex from your APK:
```bash
unzip your-app.apk classes*.dex
```

3. Convert dex to jar using dex2jar:
```bash
d2j-dex2jar classes.dex -o classes.jar
```

4. Run Vineflower on the jar:
```bash
java -jar vineflower.jar classes.jar output_directory
```

Would you like me to provide more specific guidance for any of these steps? Also, are you working with multiple dex files or just a single classes.dex?

Remember that when decompiling apps:
- Respect intellectual property rights and terms of service
- Be aware that some apps may have anti-tampering protections
- The decompiled code might not be perfect due to obfuscation or optimizations

**Comment by cagnulein** [comment]
unfortunately

/*
$VF: Unable to decompile class
Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
java.lang.IllegalStateException: Couldn't find method d (Ljava/lang/String;)Lpy/q; in class com/echelonfit/equipment/encryption/UnlockEquipment
  at org.vineflower.kotlin.struct.KFunction.parse(KFunction.java:154)
  at org.vineflower.kotlin.KotlinWriter.writeClass(KotlinWriter.java:223)
  at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:474)
  at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:191)
  at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:187)
*/

**Comment by cagnulein** [comment]
Note for me: let's see if the kotlin decompiler decompile correctly the
module with the handle receive data

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 gen 2025 alle 04:18 stale[bot] ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@mbfit1 i'm back here with a question: this device works only if your phone has internet connectivity? what happen if you disable the mobile data and wifi from your phone? does the echelon app still work? it should be good to collect a bug report on this scenario

**Comment by mbfit1** [comment]
No, Ech app cannot open looks for internet

**Comment by cagnulein** [comment]
argh that's definitely a bad sign, so even for manual workouts you need internet with the app?

**Comment by mbfit1** [comment]
yes

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
i guess it's the end of the road so. the only way to achieve this is instead using the qz app directly on their tablet. does it have android? also the tablet on the treadmill requires internet?

**Comment by mbfit1** [comment]
Yes the Ech app is available on Android. Yes the treadmill tablet/screen does require internet.

Oh well.. we gave it the best try... no problem Appreciate all you have done.

Love the QZ app...

 

Marc

404.285.5671

**Comment by cagnulein** [comment]
Argh :( i guess we have to say to everyone to don't buy these devices so :(

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 14 apr 2025 alle 16:31 Marc ***@***.***> ha
scritto:
